### ISSUE TITLE
Codigos

### ISSUE THREAD

**Issue by pyre07** [Cronus-Emulator/clang#1]
![warningsnerrors](https://cloud.githubusercontent.com/assets/12450877/7641109/850247aa-fa55-11e4-9edd-08edc6a22bca.jpg)
Ola!
Aparecem Avisos e Erros quando rodo o Cronus.bat e ele comeca a ler as files do clang , tinha erros no thread.c dai consegui arrumar com minha pouca experiencia porem apareceram mais erros achei melhor postar aqui porque não consegui arrumar.

**Comment by SlexFire** [comment]
Essas novas revisões ainda precisam ser adaptadas para o clang... A correção no arquivo thread.c é apenas uma parte desta adaptação. Em breve será feita essa adaptação. Por hora recomendo usar a ultima revisão do cronus.
